import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { IdentityProvider } from "@/features/account/identity/IdentityProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* One Portal identity source for the whole app: identity chrome and
            the progress layer observe the same learner snapshot. */}
        <IdentityProvider>{children}</IdentityProvider>
      </body>
    </html>
  );
}
